package miniJava.SyntacticAnalyzer;

public enum TokenType {EOT, ID, UNOP, BINOP, NUM, CLASS, LCURL, RCURL, SEMI, VOID, LPAREN, RPAREN, PUBLIC, PRIVATE, STATIC, INT, BOOLEAN, LBRACK,
	RBRACK, COMMA, DOT, THIS, EQ, RETURN, IF, ELSE, WHILE, TRUE, FALSE, NEW}
