package miniJava.SyntacticAnalyzer;

public enum TokenType {EOT, ID, GT, LT, EQEQ, LTE, GTE, NEQ, AND, OR, NOT, PLUS, MINUS, TIMES, DIV, NUM, CLASS, LCURL, RCURL,
	SEMI, VOID, LPAREN, RPAREN, PUBLIC, PRIVATE, STATIC, INT, BOOLEAN, LBRACK,
	RBRACK, COMMA, DOT, THIS, EQ, RETURN, IF, ELSE, WHILE, TRUE, FALSE, NEW, COMMENT}
